# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('favcake', models.CharField(max_length=200)),
                ('favcolor', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('db', models.CharField(max_length=200)),
            ],
        ),
    ]
