# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
