# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180927_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
